version: '3.8'

services:
  backend:
    build:
      context: ./LanchesBack
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./LanchesFront
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
